#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Step 161 -- which numbers in the text did the CONTAINER actually recompute.

WHY THIS EXISTS
S54 section 8 makes the container canonical only if "rerun coverage" reaches
half of "the numbers the text cites". Section 9.6 reported 41/41 = 100% AND
labelled the denominator "numbers the text cites" -- but 41 is step127's
audited set, not the text's numbers, which step160 counts as 191. That is the
same denominator substitution section 10.2 already corrected once, made a
second time and given a more authoritative label. A third-party reviewer caught
it.

The honest quantity needs three sets, not two:

  A  numbers the text cites                        (step160: 191 distinct)
  B  of those, ones step127 reconciles             (audited)
  C  of B, ones whose SOURCE TABLE was regenerated by the container

Section 8's threshold is |C| / |A|. Being audited is not the same as being
recomputed: step127 checks a number against a table, and that table may have
been mounted in from the authoring machine rather than produced by the
container. Roughly half the audited numbers come from tables whose producing
script cannot run in the container at all, because their inputs are not
distributed.

  python step161_container_number_coverage.py [dir]

Outputs: 161a_container_number_coverage.tsv, 161b_console.log
"""
import glob
import io
import os
import re
import subprocess
import sys

MR = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("CQTNA_DIR") or \
     os.path.dirname(os.path.abspath(__file__))
LOG = []


def say(s=""):
    print(s, flush=True)
    LOG.append(s)


def section_tables():
    """Which result tables each step127 section reads, from its own source."""
    src = io.open(os.path.join(MR, "step127_audit_manuscript_numbers.py"),
                  encoding="utf-8").read()
    parts = re.split(r'print\("(\d[a-z]?\..*?)"\)', src)
    out = {}
    for i in range(1, len(parts), 2):
        name = parts[i].split(".")[0]
        tabs = set(re.findall(r'_find\("([0-9]{1,3}[a-z]?_[A-Za-z0-9_.]+?)"\)',
                              parts[i + 1]))
        if tabs:
            out.setdefault(name, set()).update(tabs)
    # Section 1 reads its tables at module level, before any banner is printed.
    out.setdefault("1", set()).update({
        "123d_fixed_anchor_full_grid.tsv", "126a_offgrid_attribution.tsv",
        "126c_permutation_primary.tsv", "130c_multilist_verdict.tsv",
        "141a_enrichment_decomposition.tsv", "140d_threshold.tsv",
        "141b_reviewer_conditioning.tsv",
        "85e_matched_background_fixed_anchor.tsv"})
    return out


def regenerated_prefixes():
    """Table prefixes the container produced, from the acceptance log.

    Read from 159a rather than hardcoded, so a future run that reruns more
    steps widens this automatically instead of silently leaving the figure
    stale.
    """
    path = os.path.join(MR, "159a_container_acceptance.tsv")
    if not os.path.exists(path):
        return None
    ok = set()
    for ln in io.open(path, encoding="utf-8").read().splitlines()[1:]:
        f = ln.split("\t")
        if len(f) > 3 and f[0] == "2" and f[2] == "ok":
            m = re.search(r'step(\d+[a-z]?)', f[1])
            if m:
                ok.add(m.group(1))
    return ok


def main():
    tabs = section_tables()
    ok = regenerated_prefixes()
    if ok is None:
        say("159a_container_acceptance.tsv missing; run step159 first.")
        return 1

    steps = {os.path.basename(f)[4:].split("_")[0]
             for f in glob.glob(os.path.join(MR, "step*.py"))
             + glob.glob(os.path.join(MR, "step*.R"))}

    def producer(t):
        """The step id that produced table `t`, or None.

        Two naming conventions collide here and reducing the table name to its
        digits silently picks the wrong one. In `140d_threshold.tsv` the letter
        is an OUTPUT index and the producer is step140. In
        `85e_matched_background_fixed_anchor.tsv` the letter is part of the
        STEP id and the producer is step85e -- there is no step85 output "e".
        The first version took the digits in both cases, so 85e was looked up
        as "85", which the run never records, and section 1 of step127 -- 17 of
        the numbers the text cites -- was reported as not regenerated while the
        container had in fact produced that table, with the two migrated cells
        S54 section 9.10.2 enumerates sitting in 159e_table_diff.tsv as proof.

        Resolve it by asking the repository instead of guessing: take the
        LONGEST id that prefixes the table name and actually exists as a
        script. It keeps the property the first version was written for, that
        "12_" must not be satisfied by step120, because the match is still
        against a whole step id and never a substring of a longer number.

        ⚠ WHAT THIS CHANGED, AND WHEN. The rule can withdraw credit as
        readily as grant it, but on this repository it does not: it moves
        exactly one table, 85e, and only into the regenerated set. C goes
        82 -> 96 of A = 191, i.e. 42.9% -> 50.3%, across S54 section 8's 50%
        line, by ONE number. It was written AFTER 42.9% had been observed and
        after the shortfall was known. Both of those have to be read together
        and neither cancels the other: the correction is right on the facts
        -- 159e_table_diff.tsv records the container's own 85e output, two
        migrated cells and all -- and it is also a post-observation change to
        a measurement whose threshold it then crosses by the smallest possible
        margin. S54 section 9.6 carries both figures and the ordering; do not
        quote 50.3% without them.
        """
        m = re.match(r'([0-9]{1,3}[a-z]?)_', t)
        if not m:
            return None
        full = m.group(1)
        for cand in (full, full.rstrip("abcdefghijklmnopqrstuvwxyz")):
            if cand in steps:
                return cand
        return None

    def regen(t):
        pr = producer(t)
        return pr is not None and pr in ok

    p = subprocess.run([sys.executable, "step127_audit_manuscript_numbers.py", MR],
                       cwd=MR, capture_output=True, text=True, timeout=3600)
    sec, vals = None, {}
    for ln in p.stdout.splitlines():
        m = re.match(r'^(\d[a-z]?)\.', ln.strip())
        if m:
            sec = m.group(1)
            continue
        if re.match(r'\s+(OK |MISSING)', ln):
            for v in re.findall(r"(?<![\w.\-])\d+\.\d+(?![\w])", ln):
                vals.setdefault(sec, set()).add(v)

    # Restrict to values that actually appear in the body. step127 prints
    # things the manuscript does not cite -- the sixteen Software version
    # numbers among them -- and counting those would answer a different
    # question from the one section 8 asks, with a bigger numerator.
    body = set()
    cov_p = os.path.join(MR, "160a_audit_coverage.tsv")
    if os.path.exists(cov_p):
        for ln in io.open(cov_p, encoding="utf-8").read().splitlines()[1:]:
            f = ln.split("	")
            if f:
                body.add(f[0])

    recomputed, audited_only = set(), set()
    rows = []
    for s, vs in sorted(vals.items()):
        t = tabs.get(s, set())
        is_re = bool(t) and all(regen(x) for x in t)
        vs = {v for v in vs if not body or v in body}
        (recomputed if is_re else audited_only).update(vs)
        rows.append((s, ",".join(sorted(t)), "yes" if is_re else "no", len(vs)))
    audited_only -= recomputed

    # the text's own count, from step160's output file
    total = None
    cov = os.path.join(MR, "160a_audit_coverage.tsv")
    if os.path.exists(cov):
        total = sum(1 for _ in io.open(cov, encoding="utf-8")) - 1

    say("=" * 74)
    say("what the container actually recomputed, of the numbers the text cites")
    say("=" * 74)
    say("  A  distinct values in the body            : %s"
        % (total if total else "?"))
    say("  B  of those, reconciled by step127        : %d"
        % len(recomputed | audited_only))
    say("  C  of B, source table regenerated here    : %d" % len(recomputed))
    say("     audited but NOT regenerated            : %d" % len(audited_only))
    if total:
        say()
        say("  S54 section 8 threshold is C / A >= 50%%: %d / %d = %.1f%%"
            % (len(recomputed), total, 100.0 * len(recomputed) / total))
        say()
        say("  NOTE Being audited is not being recomputed. step127 checks a number")
        say("  against a table; that table may have been mounted in from the")
        say("  authoring machine. The tables behind the coloc, SMR, meta,")
        say("  single-cell and chromatin numbers are not regenerated in the")
        say("  container because their inputs are not distributed.")

    with io.open(os.path.join(MR, "161a_container_number_coverage.tsv"), "w",
                 encoding="utf-8", newline="\n") as f:
        f.write("section\tsource_tables\tregenerated_in_container\tn_values\n")
        for r in rows:
            f.write("\t".join(str(x) for x in r) + "\n")
    say()
    say("  wrote 161a_container_number_coverage.tsv")
    return 0


if __name__ == "__main__":
    rc = main()
    io.open(os.path.join(MR, "161b_console.log"), "w",
            encoding="utf-8", newline="\n").write("\n".join(LOG) + "\n")
    sys.exit(rc)
