#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Step 159 -- execute S54: the container acceptance run.

Executes manuscript/PREREG_container_canonical.md (S54), committed 2026-09-07
before the image existed, as amended in S54 section 10.1 (before the image
existed, and before any result was observed).

WHY THE ORDER IS WHAT IT IS -- THIS IS THE POINT OF THE SCRIPT
The first version ran step127 first, against the tables mounted in from the
authoring machine. That proves the repository arrived intact and nothing more:
it cannot show that the container reproduces the manuscript, because the
container had not yet produced anything. Third-party review caught it. The
order now is

  phase 0  snapshot the incoming tables as an immutable baseline
  phase 1  gate: package suite + the four audits, as a MOUNT CHECK only
  phase 2  rerun every analysis that can run here
  phase 3  ACCEPTANCE: rerun the four audits, now against container tables
  phase 4  diff container tables against the phase-0 baseline, cell by cell

Phase 3 is the tier-one criterion in S54 section 2. Phase 1 is not.

A failed step cannot leave tracked files worse than it found them, either:
`run()` diffs tracked files immediately before and after each step and, on
failure, reverts exactly what that step touched (needs `git` in the image;
the acceptance Dockerfile installs it after the expensive R layer so this
does not invalidate that cache). Found necessary the first time this ran:
step158 failed for a legitimate, documented reason -- its external inputs are
not part of the deposit -- and in doing so overwrote a prior run's console
log with a one-line failure message. Nothing was lost from git history, but a
tool meant for strangers to rerun should not depend on someone noticing that
by hand every time.

  docker build -f container/Dockerfile -t cqtna-audit:0.3.0 .
  docker run --rm -v "$PWD:/repo" -w /repo cqtna-audit:0.3.0 \
      python3 step159_container_acceptance.py /repo

WHAT IT DOES NOT DO
It does not adopt anything. S54 section 4 is all-or-nothing and the choice
between canonical and falling back to (a) is a person's, made against this
report and recorded in S54 section 9.

Outputs: 159a_container_acceptance.tsv, 159b_console.log,
         159d_baseline/ (immutable), 159e_table_diff.tsv
"""
import filecmp
import glob
import io
import os
import platform
import re
import shutil
import subprocess
import sys
import time

# Flags are stripped before the positional directory is read, so
# --reuse-baseline cannot be mistaken for the repository path.
_FLAGS = set(a for a in sys.argv[1:] if a.startswith("-"))
_POS = [a for a in sys.argv[1:] if not a.startswith("-")]
REUSE_BASE = "--reuse-baseline" in _FLAGS

MR = (_POS[0] if _POS
      else os.environ.get("CQTNA_DIR") or os.path.dirname(os.path.abspath(__file__)))
BASE = os.path.join(MR, "159d_baseline")
LOG = []

AUDITS = [
    ("step127 numbers", ["python3", "step127_audit_manuscript_numbers.py", MR]),
    ("step153 pre-registrations", ["python3", "step153_prereg_inventory.py", MR]),
    ("step154 cross-references", ["python3", "step154_crossref_audit.py", MR]),
    ("step155 reference order", ["python3", "step155_renumber_references.py", MR]),
]

# S54 section 3, groups 3 to 6, in S54's order.
ANALYSES = [
    ("step140 identity", ["Rscript", "step140_estimator_identity.R", MR]),
    ("step141 decomposition", ["Rscript", "step141_enrichment_decomposition.R", MR]),
    ("step101 effect-size matching", ["python3", "step101_effect_size_matching.py", MR]),
    ("step147 fine-mapping", ["Rscript", "step147_finemap_decomposition.R", MR]),
    ("step151 corpus scan", ["python3", "step151_instrument_count_in_literature.py", MR]),
    ("step156 C6 score", ["python3", "step156_estimator_provenance_coding.py", MR, "score"]),
    ("step158 visibility", ["python3", "step158_visibility_overlap.py", MR, MR]),
]

# S54 section 3 group 7: everything else with its inputs present. Attempted, and
# a failure here is recorded as "not rerunnable" rather than as a discrepancy.
#
# The first version of this globbed "step1[2-5][0-9]_*.py" -- PYTHON ONLY, and
# only steps 120-159. S54 section 3 row 7 says "step*", so that under-
# implemented the pre-registration in two ways at once, and both bit. The
# producers of five of the eight tables step127 reconciles the manuscript
# against are R scripts (step124, step126, step130) or fall outside the number
# range (step85e), so they were never attempted: 18 of the 41 numbers step127
# checks were never regenerated by the container at all. Measured against
# scripts on the must-run list the first run looked like 100% coverage;
# measured against S54 section 8's actual denominator -- numbers cited in the
# text -- it was 23/41 = 56%, six points above the fallback threshold rather
# than comfortably clear of it. Logged as a post-execution amendment in S54
# section 10.2: results had already been observed when this was found, and the
# change widens what is tested rather than loosening any criterion.
#
# SECOND WIDENING, and for the same reason a second time. The glob above was
# still "step1[2-5][0-9]" -- steps 120-159 -- so the 118 scripts numbered below
# 120 had never been ATTEMPTED, which is not the same as their being unable to
# run here. Three were tried by hand (step53, step55, step104): all three ran,
# and all three produced byte-identical tables. So "the container recomputes
# 42.9% of the numbers the text cites" was measuring the glob, not the
# container. S54 section 3 row 7 says "step*" and now this does too.
#   Timing, on the record: this was changed AFTER the 42.9% figure was
#   observed and after it was seen to fall below the section 8 fallback
#   threshold. Same disclosure as section 10.2, and it has to be read the same
#   way -- widening what gets executed cannot make a criterion easier to pass,
#   but the order of events is part of the finding and is logged in S54
#   section 9.6 rather than left to the final number.
GROUP7_GLOBS = ["step*.py", "step*.R"]
# Subsumed by the glob above now; kept so the intent survives if the glob is
# ever narrowed again. The tier-one criterion in S54 section 2 is "every number
# the text cites", so the producers of the tables step127 reads are attempted
# by name regardless of where they sit in the numbering.
GROUP7_EXTRA = ["step85e_matched_background.py"]
GROUP7_SKIP = {  # already run above, or not analyses
    "step151_instrument_count_in_literature.py",
    "step152_set_identity.py", "step153_prereg_inventory.py",
    "step154_crossref_audit.py", "step155_renumber_references.py",
    "step156_estimator_provenance_coding.py", "step157_perturbseq_tpi1_lookup.py",
    "step158_visibility_overlap.py", "step159_container_acceptance.py",
    "step127_audit_manuscript_numbers.py",
    # Queries a LIVE external database (GWAS Catalog) by design -- its own
    # docstring says "the Catalog grows, so some drift is expected". A rerun
    # two weeks later legitimately returns different counts on the SAME
    # machine; that is not a container finding and running it here only
    # produces noise S54 is not asking about. Confirmed by inspection after
    # the first acceptance run showed 68 changed lines here with nothing
    # else to explain them but the calendar.
    "step143_list_provenance.py",
    # Already executed above as part of the must-run list (groups 3-5). The
    # must-run entries carry labels rather than filenames, so nothing else
    # de-duplicates them and they would otherwise run a second time --
    # step147 alone costs nine minutes for an identical result.
    "step140_estimator_identity.R", "step141_enrichment_decomposition.R",
    "step147_finemap_decomposition.R",
    # ⚠ REGENERATES 150a_environment.lock, the record of the AUTHORING
    # machine's package versions. Running it here would overwrite that with
    # the container's own versions and destroy the very baseline S54 section 1
    # compares against -- and it would do it silently, since the file would
    # still be present and still parse. Never in group 7.
    "step150_environment_lock.R",
    # ⚠ Brought in by the widened glob, and excluded for step150's reason, not
    # for convenience: these two are package INSTALLERS, not analyses. They
    # produce no table. What they do produce is a different R library than the
    # one phase 1 just certified closed against 150a_environment.lock
    # (226/226), and every R script after them in the same run would then be
    # executing in an environment no longer described by that check --
    # silently, because the run would carry on looking fine. step46 also pulls
    # BSgenome.Hsapiens.UCSC.hg38, ~800 MB, over the network.
    #   Everything ELSE the widened glob brings in is attempted, including the
    # scripts that query live external services and the ones whose GEO inputs
    # were never part of the deposit. Those fail, and "not rerunnable" with a
    # reason is a result S54 wants; skipping them would be the thing this
    # amendment exists to stop.
    "step20_install.R", "step46_install_motif.R",
    # ⚠ Added 2026-09-11 on evidence, not on suspicion. These three are data
    # ACQUISITION, not analysis: they fetch GEO archives into D:/Downloads,
    # which is outside the repository and which the container cannot see, so
    # inside the image that path resolves to /repo/D:/Downloads and the
    # download lands IN THE REPOSITORY. On the 2026-09-11 run that is exactly
    # what happened -- 20.8 GB written into the working tree, on a disk with
    # 14 GB to spare, every file a byte-size duplicate of one already sitting
    # at D:/Downloads on the authoring machine. step51 had to be killed at
    # 1942 s to stop it (recorded rc=-15, a termination, not a natural
    # failure).
    #   Their absence costs no coverage. What they fetch is the single-cell,
    # spatial and chromatin input the deposit does not distribute, so the
    # analyses downstream of them are "not rerunnable" either way; running
    # the downloader only changes whether the reader's disk fills up first.
    # ⚠ And the fix is NOT to mount D:/Downloads into the image: S54's whole
    # premise is that a reader has the repository and nothing else. Mounting
    # it would measure a deposit that does not exist.
    "step33_get_GSE282266.py", "step41_get_GSE166188.py",
    "step51_get_GSE199994.py",
    # ⚠ Added 2026-09-11, and this one is not about cost or noise -- rerunning
    # these DESTROYS EVIDENCE. step94b queries the live GWAS Catalog REST API
    # for known-locus lists; step94c rebuilds 94d_grid.tsv from them. But
    # 94d_grid.tsv is not a live result: PREREG_generality_grid.md §8.2 voided
    # its lung and colorectal rows for bad coordinates, and step119 copies
    # those two rows out of it VERBATIM so the rebuilt grid can display them
    # marked "void_bad_coords" beside a fixed explanation -- "a background of
    # only 2/559 and 5/559 known loci against 58/554 for melanoma".
    #   Rerun on today's Catalog, those rows come back as bg_known 70 and 203,
    # fold 2.99 and 2.00. Measured, not predicted: running step119 after this
    # run's step94c produced a 119a_grid_main.tsv whose void rows carry the
    # corrected numbers while the sentence beside them still says 2/559 and
    # 5/559. The row would then refute the reason for its own voiding, and the
    # record of the defect would be gone.
    #   Ordering hid it here: group 7 runs step119 before step94c (string
    # order), so step119 read the pre-run 94d and 119a came out unchanged. A
    # reader running them the other way round gets the contradiction. 94d and
    # 94e are frozen evidence, not results; they are restored to their
    # committed state and their producers do not run.
    "step94b_known_loci.py", "step94c_grid.py",
}

# Tier-two tables (S54 section 2) plus the ones the manuscript quotes from.
WATCH = [
    "140a_identity_check.tsv", "140d_threshold.tsv",
    "141a_enrichment_decomposition.tsv", "141b_reviewer_conditioning.tsv",
    "101a_zdist.tsv", "101b_matched.tsv", "101c_stratified.tsv",
    "101d_zonly_model.tsv", "147a_finemap_decomposition.tsv",
    "151a_estimator_usage.tsv", "156c_C6_agreement.tsv", "156e_C6_result.tsv",
    "158a_visibility_2x2.tsv", "158b_visibility_by_decile.tsv",
    "123d_fixed_anchor_full_grid.tsv", "130c_multilist_verdict.tsv",
    "126a_offgrid_attribution.tsv", "85e_matched_background_fixed_anchor.tsv",
    # Added 2026-09-08. step127 reads this for the two permutation calibration
    # figures and it was the one audited table absent from WATCH, so phase 4
    # never compared it -- found by hand, which is exactly the failure mode
    # WATCH_GUARD below now makes mechanical.
    "126c_permutation_primary.tsv",
    # Added 2026-09-11, on the guard's own report. Widening step127 from 41
    # numbers to 174 widened the set of tables it reads, and WATCH did not
    # follow: the guard listed EIGHTEEN audited tables phase 4 was not
    # comparing. Ten of them the container had actually regenerated, so a
    # moved cell in any of them would have gone unreported -- the same defect
    # 126c had, at ten times the size, caught mechanically this time instead
    # of by hand.
    #   ⚠ For the 2026-09-11 run itself these were still uncompared, and
    # adding them here does not retroactively compare them: 159d_baseline/
    # holds only the eighteen tables phase 0 snapshotted before the first
    # container run, and re-snapshotting now would compare the container
    # against itself. They were checked a different way instead, and it is
    # recorded in S54 section 9.11 rather than left implied: all ten were last
    # committed between 2026-08-19 and 08-24, before any container existed,
    # and all ten are unmodified in the working tree after this run -- so they
    # are byte-identical between the authoring machine and the container,
    # across two container runs. The other eight were never regenerated here
    # (their producers fail on absent inputs or on a hardcoded authoring path)
    # and so have nothing to compare.
    "104c_validation.tsv", "128a_known_kb_sweep.tsv",
    "128b_locus_kb_sweep.tsv", "130a_multilist_main.tsv",
    "135a_hcc_gate_distance.tsv", "138a_transport_main.tsv",
    "138b_transport_verdict.tsv", "139c_leave_one_out.tsv",
    "142a_power_matched.tsv", "148a_litaudit_corpus.tsv",
    "148b_litaudit_doublecoded.tsv", "23g_ST_within_lymphoid.tsv",
    "44b_family_composition.tsv", "53b_calibration.tsv",
    "55a_recovery_by_locus_class.tsv", "68c_tests.tsv",
    "85a_HCC_high_annotated.tsv", "85a_HCC_low_annotated.tsv",
]


def say(s=""):
    print(s, flush=True)
    LOG.append(s)


def argv_guard(paths):
    """Does any script mean something OTHER than the repository by argv[1]?

    This runner invokes every group-7 script as `<runner> <script> <MR>`, so it
    is asserting that argv[1] is the repository directory. The 2026-09-11
    portability pass then gave 102 scripts `MR = sys.argv[1] ...` on that
    assumption -- and two of them already used argv[1] for something else:
    step91 reads it as the path to a PMID JSON, step21 as a ligand-receptor
    table (with argv[2] as a tag). Both would have silently set MR to a
    filename on the authoring machine.

    The check that passed those two was the wrong kind: it verified the SHAPE
    of every changed line and reported zero violations, which says nothing
    about what argv[1] already meant. So the check lives here now, next to the
    call that makes the assumption, rather than in a one-off script someone
    has to remember to run.
    """
    bad = []
    for p in paths:
        if not p.endswith(".py") or not os.path.exists(p):
            continue
        try:
            s = io.open(p, encoding="utf-8", errors="replace").read()
        except Exception:
            continue
        m = re.search(r'MR\s*=\s*\(?sys\.argv\[(\d)\]', s)
        if not m:
            continue
        idx = m.group(1)
        rest = s[m.end():]
        if re.search(r'sys\.argv\[%s\]' % idx, rest):
            bad.append((os.path.basename(p), idx))
    if bad:
        say("  ⚠ argv guard: %d script(s) read argv[%s] for something other"
            % (len(bad), ", ".join(sorted({b[1] for b in bad}))))
        say("    than the repository, and would take this runner's MR for it:")
        for n, i in bad:
            say("      %-44s argv[%s] reused" % (n, i))
        say("    Give MR the next free index, as step157/step158 do.")
    else:
        say("  argv guard: no script reuses the index it takes MR from.")


def watch_guard():
    """Every table step127 reconciles the manuscript against must be watched.

    S54 section 2's tier-one criterion is "every number the text cites", and
    phase 4 is what reports a number that moved. A table step127 reads but
    WATCH omits is therefore invisible to phase 4 -- the acceptance still
    passes, and the moved value is simply never mentioned. That happened:
    126c_permutation_primary.tsv, the permutation calibration, was audited by
    step127 and absent from WATCH, and it took a hand comparison to notice.
    Rather than add the one name and move on, this derives the set from
    step127's own source so the next table added there cannot slip through.
    """
    src_path = os.path.join(MR, "step127_audit_manuscript_numbers.py")
    try:
        src = io.open(src_path, encoding="utf-8").read()
    except Exception as e:
        say("  WATCH guard: cannot read step127 (%s); guard skipped." % e)
        return
    reads = set(re.findall(r'["\']([0-9]{2,3}[a-z]_[A-Za-z0-9_]+\.tsv)["\']', src))
    missing = sorted(reads - set(WATCH))
    if missing:
        say("  ⚠ WATCH guard: step127 audits %d table(s) phase 4 does not"
            " compare:" % len(missing))
        for m in missing:
            say("      %s" % m)
        say("    A number that moved in these would pass unreported. Add them")
        say("    to WATCH.")
    else:
        say("  WATCH guard: all %d table(s) step127 audits are watched." % len(reads))


def _git(args):
    try:
        p = subprocess.run(["git"] + args, cwd=MR, capture_output=True,
                           text=True, timeout=60)
        return p.returncode, (p.stdout or "")
    except Exception:
        return 1, ""


def _git_free_version(pkg):
    """Installed version of an R package, or ("", None) if it is not there."""
    try:
        p = subprocess.run(
            ["Rscript", "-e",
             'cat(as.character(packageVersion("%s")))' % pkg],
            cwd=MR, capture_output=True, text=True, timeout=120)
        return p.returncode, (p.stdout or "").strip()
    except Exception:
        return 1, ""


def run(label, cmd, timeout=7200):
    # A step that cannot succeed here should not be able to leave tracked
    # files worse off than it found them. Discovered the hard way: step158
    # failed for a documented, legitimate reason (its external inputs are not
    # part of the deposit) and, in doing so, overwrote 158c_console.log --
    # 33 lines of a prior successful run's evidence -- with one line saying
    # it could not run this time. Nothing was lost from git history, but a
    # tool meant to be rerun by strangers should not depend on a human
    # noticing that in every future run. `git diff --name-only` before and
    # after brackets exactly what THIS step touched; on failure, revert only
    # that set, never anything a different step is responsible for.
    rc_git, before = _git(["diff", "--name-only"])
    before = set(before.split()) if rc_git == 0 else None

    t0 = time.time()
    try:
        p = subprocess.run(cmd, cwd=MR, capture_output=True, text=True,
                           timeout=timeout)
        rc, out = p.returncode, (p.stdout or "") + (p.stderr or "")
    except FileNotFoundError as e:
        rc, out = 127, "not found: %s" % e
    except subprocess.TimeoutExpired:
        rc, out = 124, "timed out"
    say("  %-34s %-12s %6.1f s"
        % (label, "ok" if rc == 0 else "FAIL rc=%d" % rc, time.time() - t0))
    if rc != 0:
        for line in [x for x in out.splitlines() if x.strip()][-8:]:
            say("      | " + line[:108])
        if before is not None:
            rc_git, after = _git(["diff", "--name-only"])
            touched = (set(after.split()) - before) if rc_git == 0 else set()
            if touched:
                _git(["checkout", "--"] + sorted(touched))
                say("      reverted (failed step touched tracked files): %s"
                    % ", ".join(sorted(touched)))
    return rc, out


def cellwise_diff(a, b, limit=40):
    """Report changed cells, not just changed files: a moved digit is what S54
    section 5 has to enumerate."""
    try:
        ra = io.open(a, encoding="utf-8", errors="replace").read().split("\n")
        rb = io.open(b, encoding="utf-8", errors="replace").read().split("\n")
    except Exception as e:
        return [("<unreadable>", "", str(e))]
    out = []
    if ra and rb and ra[0] != rb[0]:
        out.append(("<header>", ra[0][:60], rb[0][:60]))
    for i in range(max(len(ra), len(rb))):
        la = ra[i] if i < len(ra) else "<missing row>"
        lb = rb[i] if i < len(rb) else "<missing row>"
        if la == lb:
            continue
        ca, cb = la.split("\t"), lb.split("\t")
        for j in range(max(len(ca), len(cb))):
            x = ca[j] if j < len(ca) else ""
            y = cb[j] if j < len(cb) else ""
            if x != y:
                out.append(("row %d col %d" % (i, j + 1), x[:40], y[:40]))
                if len(out) >= limit:
                    return out
    return out


def main():
    say("container acceptance run (S54, as amended in section 10.1)")
    say("  when     : %s" % time.strftime("%Y-%m-%d %H:%M:%S"))
    say("  platform : %s" % platform.platform())
    say("  python   : %s" % platform.python_version())
    rows = []

    # ------------------------------------------------------------- phase 0
    say()
    say("=" * 74)
    say("phase 0 -- immutable baseline of the tables mounted in")
    say("=" * 74)
    if os.path.isdir(BASE) and not REUSE_BASE:
        say("  159d_baseline/ already exists; refusing to overwrite it.")
        say("  A baseline taken after a rerun is not a baseline. Remove it")
        say("  deliberately if you really are starting over, or pass")
        say("  --reuse-baseline to compare against the one already there.")
        return 2
    if os.path.isdir(BASE):
        # The legitimate case this exists for: the executor was defective, not
        # the environment. Re-running to widen coverage must compare against
        # the ORIGINAL authoring-machine tables, and by now the working tree
        # holds container output -- so re-snapshotting would silently turn the
        # comparison into container-vs-container and report no differences at
        # all. Reuse is therefore the only correct behaviour here, and it is
        # opt-in and logged rather than the default.
        say("  --reuse-baseline: comparing against the EXISTING 159d_baseline/,")
        say("  which holds the authoring-machine tables snapshotted before the")
        say("  first container run. Not re-snapshotted: the working tree now")
        say("  holds container output, and a baseline taken from that would")
        say("  compare the container against itself.")
        say("  baseline holds %d table(s)."
            % len([x for x in os.listdir(BASE) if x.endswith(".tsv")]))
    else:
        os.makedirs(BASE)
        kept = 0
        for f in WATCH:
            src = os.path.join(MR, f)
            if os.path.exists(src):
                shutil.copy2(src, os.path.join(BASE, f))
                kept += 1
        say("  copied %d of %d watched tables into 159d_baseline/" % (kept, len(WATCH)))

    # ------------------------------------------------------------- phase 1
    say()
    say("=" * 74)
    say("phase 1 -- GATE. Mount check only, NOT the acceptance test")
    say("=" * 74)
    say("  These audits run against the tables that arrived with the repository.")
    say("  Passing here says the mount is intact. It says nothing yet about")
    say("  whether the container reproduces them (S54 section 10.1).")
    gate_bad = False

    # S54 section 8's FIRST stop condition: dependency resolution not matching
    # 150a means record the difference, fix the image, and do not rerun
    # damaged. Both 2026-09-07/08 runs violated it without anyone noticing,
    # because nothing checked -- the slim image had 42 of the lock's 226
    # packages at the right version and 11 at outright wrong ones, and it took
    # the author asking whether the full closure had been used to surface it
    # (S54 section 9.9). The full image now writes this report at build time;
    # the gate reads it so the rule is enforced by the run rather than by
    # someone remembering to look.
    rep = "/opt/150a_closure_report.tsv"
    if os.path.exists(rep):
        mis = ab = ok = late = 0
        bad = []
        for ln in io.open(rep, encoding="utf-8").read().splitlines()[1:]:
            f = ln.split("	")
            if len(f) < 4:
                continue
            if f[3] == "match":
                ok += 1
            elif f[3] == "later-layer":
                # The build wrote this report before installing cqtna from
                # source, so "later-layer" means "not installed YET, verify
                # now" -- not "ignore me". Counting it as a mismatch failed
                # the gate on a correct image; waving it through would let a
                # genuinely missing package pass. So actually go and look.
                rc_v, out_v = _git_free_version(f[0])
                if rc_v == 0 and out_v == f[1]:
                    ok += 1
                    late += 1
                else:
                    mis += 1
                    bad.append("%s %s -> %s (later-layer, checked at run time)"
                               % (f[0], f[1], out_v or "<absent>"))
            elif f[3] == "absent":
                ab += 1
            else:
                mis += 1
                bad.append("%s %s -> %s" % (f[0], f[1], f[2]))
        say("  150a closure: %d match, %d MISMATCH, %d absent%s" % (ok, mis, ab,
            " (%d verified at run time)" % late if late else ""))
        rows.append(dict(phase=1, step="150a closure",
                         status="ok" if mis == 0 else "MISMATCH", rc=mis))
        if mis:
            for b in bad[:20]:
                say("      %s" % b)
            say("  ⚠ S54 section 8: dependency resolution does not match 150a.")
            say("  Fix the image before rerunning. Not a run to interpret.")
            gate_bad = True
    else:
        say("  ⚠ no /opt/150a_closure_report.tsv in this image, so whether its")
        say("  closure matches 150a is UNVERIFIED. S54 section 8 requires that")
        say("  to be known, not assumed -- this is what section 9.9 records")
        say("  going wrong. Build container/Dockerfile, which writes it.")
        rows.append(dict(phase=1, step="150a closure",
                         status="unverified", rc=-1))
        gate_bad = True

    rc, _ = run("cqtna testthat", ["Rscript", "-e",
                                   'testthat::test_local("cqtna_r")'])
    rows.append(dict(phase=1, step="cqtna testthat",
                     status="ok" if rc == 0 else "FAIL", rc=rc))
    gate_bad |= rc != 0
    for label, cmd in AUDITS:
        rc, _ = run(label + " (pre)", cmd)
        rows.append(dict(phase=1, step=label + " (pre)",
                         status="ok" if rc == 0 else "FAIL", rc=rc))
        gate_bad |= rc != 0
    if gate_bad:
        say()
        say("  GATE FAILED. The environment or the mount is not ready.")
        say("  S54 section 8 forbids going on to explain individual numbers.")
        write_rows(rows)
        return 2

    # ------------------------------------------------------------- phase 2
    say()
    say("=" * 74)
    say("phase 2 -- rerun the analyses; these produce the container's tables")
    say("=" * 74)
    for label, cmd in ANALYSES:
        rc, _ = run(label, cmd)
        rows.append(dict(phase=2, step=label,
                         status="ok" if rc == 0 else "not rerunnable", rc=rc))

    say()
    say("  group 7 -- every other numbered step whose inputs are present")
    cand = []
    for g in GROUP7_GLOBS:
        cand += glob.glob(os.path.join(MR, g))
    cand = sorted(cand)
    cand += [os.path.join(MR, x) for x in GROUP7_EXTRA]
    argv_guard(cand)
    done = set()
    for path in cand:
        name = os.path.basename(path)
        if name in GROUP7_SKIP or name in done or not os.path.exists(path):
            continue
        done.add(name)
        runner = "Rscript" if name.endswith(".R") else "python3"
        rc, _ = run(name, [runner, name, MR], timeout=3600)
        rows.append(dict(phase=2, step=name,
                         status="ok" if rc == 0 else "not rerunnable", rc=rc))

    # ------------------------------------------------------------- phase 3
    say()
    say("=" * 74)
    say("phase 3 -- ACCEPTANCE. The same audits, now against container tables")
    say("=" * 74)
    acc_bad = 0
    for label, cmd in AUDITS:
        rc, _ = run(label + " (post)", cmd)
        rows.append(dict(phase=3, step=label + " (post)",
                         status="ok" if rc == 0 else "FAIL", rc=rc))
        acc_bad += rc != 0

    # ------------------------------------------------------------- phase 4
    say()
    say("=" * 74)
    say("phase 4 -- container tables against the phase-0 baseline")
    say("=" * 74)
    watch_guard()
    say()
    moved, diffs = [], []
    for f in WATCH:
        a, b = os.path.join(BASE, f), os.path.join(MR, f)
        if not os.path.exists(a) or not os.path.exists(b):
            continue
        if filecmp.cmp(a, b, shallow=False):
            continue
        moved.append(f)
        for where, was, now in cellwise_diff(a, b):
            diffs.append(dict(table=f, where=where, baseline=was, container=now))
    if not moved:
        say("  every watched table is byte-identical to the baseline.")
    else:
        say("  %d table(s) differ:" % len(moved))
        for f in moved:
            n = sum(1 for d in diffs if d["table"] == f)
            say("    %-44s %d changed cell(s)" % (f, n))
    with io.open(os.path.join(MR, "159e_table_diff.tsv"), "w",
                 encoding="utf-8", newline="\n") as fh:
        fh.write("table\twhere\tbaseline\tcontainer\n")
        for d in diffs:
            fh.write("%s\t%s\t%s\t%s\n"
                     % (d["table"], d["where"], d["baseline"], d["container"]))
    say("  wrote 159e_table_diff.tsv")

    write_rows(rows)
    say()
    say("=" * 74)
    if acc_bad:
        say("VERDICT: %d audit(s) FAILED in phase 3." % acc_bad)
        say("Those failures are the numbers that moved. Enumerate every one in")
        say("S54 section 9.2 and every flipped verdict in 9.3, then apply the")
        say("migration rule in S54 section 5. Do not adopt selectively:")
        say("S54 section 4 is all-or-nothing.")
        return 1
    say("VERDICT: phase 3 audits all pass against container-produced tables,")
    say("and %d watched table(s) differ from the baseline." % len(moved))
    say()
    say("This is still NOT a decision. Read 159e_table_diff.tsv, fill S54")
    say("section 9, and choose canonical or fall back to (a) with reasons.")
    return 0


def write_rows(rows):
    with io.open(os.path.join(MR, "159a_container_acceptance.tsv"), "w",
                 encoding="utf-8", newline="\n") as f:
        f.write("phase\tstep\tstatus\trc\n")
        for r in rows:
            f.write("%s\t%s\t%s\t%s\n"
                    % (r["phase"], r["step"], r["status"], r["rc"]))


if __name__ == "__main__":
    rc = main()
    io.open(os.path.join(MR, "159b_console.log"), "w",
            encoding="utf-8", newline="\n").write("\n".join(LOG) + "\n")
    raise SystemExit(rc)
