#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Step 152 -- fill in the three things only the author can supply.

WHY THIS IS A SCRIPT AND NOT A CHECKLIST
The maintainer identity and the repository DOI are not in one place. They are in
a package DESCRIPTION, a LICENSE, a CITATION.cff, a .zenodo.json, a generated
.Rd file, the manuscript's code-availability paragraph, the deposit README and
the release checklist's suggested wording. RELEASE.md section 3 tells the author
to grep for them by hand. A hand grep is exactly the kind of step that leaves one
file behind, and the file it leaves behind is the one nobody reads again until a
reviewer does.

  python step152_set_identity.py                 # report what is still unfilled
  python step152_set_identity.py --name "Ada Lovelace" \
      --email ada@example.org --orcid 0000-0002-1825-0097 \
      --github ada/cqtna-audit --doi 10.5281/zenodo.1234567 --commit a1b2c3d

Every flag is optional; whatever is supplied is filled in, and --check is re-run
afterwards so the exit status says whether anything is still outstanding.

WHAT IT DOES NOT DO
It does not mint the DOI, create the repository or build the container. Those are
in DEPOSIT.md section 5, cqtna_r/RELEASE.md section 3 and CONTAINER.md.
It does not touch cqtna.Rcheck/, which is a build product and is regenerated by
R CMD check.

Outputs: edits in place; prints a table of every site and its state.
"""
import io
import os
import re
import sys

MR = os.environ.get("CQTNA_DIR") or os.path.dirname(os.path.abspath(__file__))

NAME_PH = "MR audit project"
MAIL_PH = "noreply@example.com"
DOI_PH = [
    "\u27e8repository DOI\u27e9",
    "\u27e8repository DOI to be minted at submission\u27e9",
    "\u27e8Zenodo DOI\u27e9",
]
SHA_PH = "\u27e8SHA\u27e9"

# Every file that carries one of the placeholders. cqtna.Rcheck/ is excluded on
# purpose: it is a build product of the tarball and is regenerated, so patching
# it would create a copy that disagrees with its own source the next time
# R CMD check runs.
# Files where the DOI is read by a human, so it is written as a resolvable URL.
PROSE = {"DEPOSIT.md", "manuscript/MANUSCRIPT_GB.md", "cqtna_r/RELEASE.md"}

SITES = [
    ("cqtna_r/DESCRIPTION", "maintainer"),
    ("cqtna_r/LICENSE", "maintainer"),
    ("cqtna_r/CITATION.cff", "maintainer"),
    ("cqtna_r/.zenodo.json", "maintainer"),
    ("cqtna_r/man/cqtna-package.Rd", "maintainer (generated -- see note)"),
    ("cqtna_r/RELEASE.md", "DOI + commit"),
    ("DEPOSIT.md", "DOI"),
    ("manuscript/MANUSCRIPT_GB.md", "DOI"),
]


def read(p):
    return io.open(os.path.join(MR, p), encoding="utf-8").read()


def write(p, t):
    io.open(os.path.join(MR, p), "w", encoding="utf-8", newline="\n").write(t)


def outstanding(t):
    # Judge the text a reader sees, not the commands that search for leftovers:
    # the freeze checklist's grep must keep the placeholder literals, and
    # counting those as unfilled would make "all sites filled" unreachable.
    t = "\n".join(ln for ln in t.split("\n")
                  if not re.search(r"\b(grep|rg|findstr|Select-String)\b", ln))
    out = []
    if NAME_PH in t:
        out.append("name")
    if MAIL_PH in t:
        out.append("email")
    for d in DOI_PH:
        if d in t:
            out.append("DOI")
            break
    if SHA_PH in t:
        out.append("commit")
    return out


def main(argv):
    opt = {}
    i = 0
    while i < len(argv):
        a = argv[i]
        if a.startswith("--") and i + 1 < len(argv) and not argv[i + 1].startswith("--"):
            opt[a[2:]] = argv[i + 1]
            i += 2
        elif a.startswith("--"):
            opt[a[2:]] = True
            i += 1
        else:
            i += 1

    name = opt.get("name")
    given = opt.get("given")
    family = opt.get("family")
    email = opt.get("email")
    orcid = opt.get("orcid")
    doi = opt.get("doi")
    commit = opt.get("commit")
    github = opt.get("github")

    if doi and doi.lower().startswith("https://doi.org/"):
        doi = doi[len("https://doi.org/"):]
    if orcid and orcid.lower().startswith("https://orcid.org/"):
        orcid = orcid[len("https://orcid.org/"):]
    if orcid and not re.match(r"^\d{4}-\d{4}-\d{4}-\d{3}[\dX]$", orcid):
        print("refusing: --orcid must look like 0000-0002-1825-0097")
        return 2
    # ⚠ --given/--family without --name used to fill NOTHING. The substitution
    # loop below only ever reads `name`, so the placeholder name survived in all
    # five metadata files; _fix_person then searched DESCRIPTION for
    # person("<given> <family>" and found the placeholder instead; and
    # _add_orcid, which waits for the placeholder to be gone, silently wrote the
    # ORCID nowhere. DEPOSIT.md section 5 documents exactly that invocation, so
    # the documented command was the one that did not work. Found 2026-09-13 on
    # its first real use.
    if not name and given and family:
        name = "%s %s" % (given, family)

    changed = []
    for path, _kind in SITES:
        full = os.path.join(MR, path)
        if not os.path.exists(full):
            continue
        t0 = read(path)
        t = t0
        if name:
            t = _replace_outside_checks(t, NAME_PH, name)
        if email:
            t = _replace_outside_checks(t, MAIL_PH, email)
        if doi:
            # Prose cites a resolvable URL; metadata files want the bare DOI.
            rendered = ("https://doi.org/" + doi
                        if path in PROSE else doi)
            for d in DOI_PH:
                t = t.replace(d, rendered)
        if commit:
            t = t.replace(SHA_PH, commit)
        if t != t0:
            write(path, t)
            changed.append(path)

    # The structured metadata files carry fields that are not simple
    # substitutions: an ORCID has nowhere to go in a plain name string.
    if name or given or family:
        _fix_person(name, given, family, changed)
    if name or email:
        _fill_title_page(name, email, changed)
    if orcid:
        _add_orcid(orcid, changed)
    if github:
        _add_github(github, changed)

    print("=" * 74)
    print("identity and DOI sites")
    print("=" * 74)
    bad = 0
    for path, kind in SITES:
        full = os.path.join(MR, path)
        if not os.path.exists(full):
            print("  %-40s  %s" % (path, "ABSENT"))
            continue
        left = outstanding(read(path))
        if left:
            bad += 1
        print("  %-40s  %-28s %s"
              % (path, kind,
                 "still unfilled: " + ", ".join(sorted(set(left))) if left else "filled"))

    if changed:
        print("\nedited: " + ", ".join(sorted(set(changed))))
        print("\n[!] cqtna_r/man/*.Rd is generated by roxygen2 from DESCRIPTION.")
        print("  It was patched here so the tarball is consistent without a")
        print("  roxygen run, but the next `roxygen2::roxygenise()` is what makes")
        print("  it authoritative. Re-run R CMD check before tagging.")
        print("[!] cqtna.Rcheck/ was deliberately not touched; it is a build product.")

    left2 = _brackets(["manuscript/MANUSCRIPT_GB.md", "DEPOSIT.md",
                       "cqtna_r/RELEASE.md"])
    if left2:
        print()
        print("=" * 74)
        print("other placeholders still bracketed")
        print("=" * 74)
        for path, what in left2:
            print("  %-40s  %s" % (path, what))
        bad += len(left2)

    print("\n%s" % ("all sites filled" if bad == 0
                    else "%d placeholder(s) still outstanding" % bad))
    return 0 if bad == 0 else 1


def _replace_outside_checks(text, old, new):
    """Replace a placeholder everywhere EXCEPT inside a command that searches for it.

    cqtna_r/RELEASE.md's freeze checklist carries
        grep -rn "OWNER\\|noreply@example.com\\|MR audit project" ...
    whose whole job is to find leftover placeholders. A blind str.replace turned
    it into a grep for the author's real address -- which is guaranteed to be
    present once filled, so the check could only ever report failure, and the
    one tool meant to confirm the placeholders are gone would have been broken
    by the act of removing them. Lines that search are left as they are.
    """
    out = []
    for ln in text.split("\n"):
        if old in ln and re.search(r"\b(grep|rg|findstr|Select-String)\b", ln):
            out.append(ln)
        else:
            out.append(ln.replace(old, new))
    return "\n".join(out)


def _fix_person(name, given, family, changed):
    """R's person() takes given and family separately. person("Ada Lovelace")
    records a mononym whose given name is the whole string, which citation()
    then renders wrongly. Split when we safely can, and say so when we cannot."""
    p = "cqtna_r/DESCRIPTION"
    t = read(p)
    if given and family:
        g, f = given, family
    elif name and " " in name.strip():
        parts = name.strip().rsplit(" ", 1)
        g, f = parts[0], parts[1]
    else:
        print("[!] --name has no space, so person() records it as a single")
        print("    given name. If that is wrong for your name, re-run with")
        print("    --given and --family.")
        return
    t2 = re.sub(r'person\("%s"' % re.escape(name if name else g + " " + f),
                'person("%s", "%s"' % (g, f), t, count=1)
    if t2 != t:
        write(p, t2)
        changed.append(p)


def _fill_title_page(name, email, changed):
    """The manuscript has no author block until someone writes one. What these
    two flags can fill is filled; the rest stays visibly bracketed."""
    p = "manuscript/MANUSCRIPT_GB.md"
    t0 = t = read(p)
    if name:
        # ⟨author list⟩ is deliberately NOT filled from --name. The flag names
        # the package maintainer; the author list is every author of the paper,
        # with order and affiliations, and the manuscript's own "author
        # contributions, by initials" section implies more than one. Writing the
        # maintainer in as the whole list would clear a visible blank with a
        # plausible wrong answer, which is worse than leaving it bracketed.
        t = t.replace("⟨corresponding author⟩", name)
    if email:
        t = t.replace("⟨corresponding email⟩", email)
    if t != t0:
        write(p, t)
        changed.append(p)


def _brackets(paths):
    """Every remaining angle-bracket placeholder, wherever it is. The DOI and the
    identity are not the only blanks -- funding, contributions, competing
    interests and the affiliations are too, and a submission that reaches a
    journal with one of them still bracketed is a desk reject."""
    out = []
    for path in paths:
        if not os.path.exists(os.path.join(MR, path)):
            continue
        for m in re.finditer("⟨([^⟩]{1,120})⟩", read(path)):
            out.append((path, m.group(1).split(chr(10))[0][:70]))
    return out

def _add_orcid(orcid, changed):
    """ORCID has a field of its own in three of the four metadata files."""
    # Each block below is gated on the placeholder name being gone, because the
    # ORCID attaches to the real name's entry. When that gate failed it used to
    # do nothing and say nothing -- the ORCID was simply lost. Say so now.
    for p in ("cqtna_r/DESCRIPTION", "cqtna_r/CITATION.cff", "cqtna_r/.zenodo.json"):
        if NAME_PH in read(p):
            print("[!] ORCID NOT written to %s: the placeholder name is still" % p)
            print("    there, so there is no author entry to attach it to.")
            print("    Supply --name (or --given and --family) in the same run.")
    p = "cqtna_r/DESCRIPTION"
    t = read(p)
    if "comment = c(ORCID" not in t and NAME_PH not in t:
        t2 = re.sub(r'(email\s*=\s*"[^"]+")\)',
                    r'\1,\n           comment = c(ORCID = "%s"))' % orcid, t, count=1)
        if t2 != t:
            write(p, t2)
            changed.append(p)

    p = "cqtna_r/CITATION.cff"
    t = read(p)
    if "orcid:" not in t and NAME_PH not in t:
        t2 = re.sub(r'(authors:\n  - name: "[^"]+")',
                    r'\1\n    orcid: "https://orcid.org/%s"' % orcid, t, count=1)
        if t2 != t:
            write(p, t2)
            changed.append(p)

    p = "cqtna_r/.zenodo.json"
    t = read(p)
    if '"orcid"' not in t and NAME_PH not in t:
        t2 = re.sub(r'(\{\s*\n\s*"name": "[^"]+")',
                    r'\1,\n      "orcid": "%s"' % orcid, t, count=1)
        if t2 != t:
            write(p, t2)
            changed.append(p)


def _add_github(slug, changed):
    """The release checklist names the repository; nothing else should hard-code
    a URL, so this only records it where the checklist already asks for it."""
    p = "cqtna_r/RELEASE.md"
    t = read(p)
    line = "\n**\u4ed3\u5e93**\uff1ahttps://github.com/%s\n" % slug
    if "https://github.com/%s" % slug not in t:
        t = t.replace("\u7248\u672c **0.3.0**\uff0c\u5efa\u8bae\u6807\u7b7e **`v0.3.0-paper`**\u3002",
                      "\u7248\u672c **0.3.0**\uff0c\u5efa\u8bae\u6807\u7b7e **`v0.3.0-paper`**\u3002" + line, 1)
        write(p, t)
        changed.append(p)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
