# Cross-implementation check against the Python reference.
#
# The plan for this package chose a pure-R port over a reticulate wrapper, on the
# condition that the Python implementation stays as an oracle. This is that
# oracle: `inst/extdata/reference_python.tsv` is generated by
# `python cqtna.py --demo` in the reference repository and committed alongside
# the fixtures, so the comparison runs anywhere without Python installed.
#
# If either implementation drifts, this fails. That is the entire point: two
# implementations of the same audit are only safe while something compares them.
#
# Note on precision. The reference stores values as Python round()ed them, which
# differs from sprintf at an exact .005 boundary (see R/report.R). The comparison
# is therefore made on unrounded R values against the reference to 2 decimals,
# using the same sprintf rounding the R report uses.

ref <- utils::read.delim(
  system.file("extdata", "reference_python.tsv", package = "cqtna"),
  stringsAsFactors = FALSE)
refv <- stats::setNames(as.numeric(ref$value), ref$key)

r2 <- function(v) as.numeric(sprintf("%.2f", v))
r3 <- function(v) as.numeric(sprintf("%.3f", v))

mr <- as_cqtna_mr(cqtna_demo("mr"), build = "GRCh38")
alt <- as_cqtna_mr(cqtna_demo("mr_alt"), build = "GRCh38")
kn <- suppressWarnings(as_cqtna_known(cqtna_demo("known"), build = "GRCh38"))
mm <- suppressWarnings(as_cqtna_known(cqtna_demo("mismatch"), build = "GRCh38"))

test_that("module A matches the Python reference", {
  a <- cqtna_attribution(mr, kn)
  expect_equal(a$background_loci, as.integer(refv[["A.background_loci"]]))
  expect_equal(a$background_known, as.integer(refv[["A.background_known"]]))
  expect_equal(a$significant_loci, as.integer(refv[["A.significant_loci"]]))
  expect_equal(a$significant_known, as.integer(refv[["A.significant_known"]]))
  expect_equal(r2(a$background_pct), refv[["A.background_pct"]])
  expect_equal(r2(a$fold), refv[["A.fold"]])
  expect_equal(a$fisher_p_one_sided, refv[["A.fisher_p_one_sided"]],
               tolerance = 1e-12)

  nc <- cqtna_attribution(mr, mm)
  expect_equal(r2(nc$fold), refv[["A_nc.fold"]])
  expect_equal(nc$fisher_p_one_sided, refv[["A_nc.fisher_p_one_sided"]],
               tolerance = 1e-12)
})

test_that("module B matches the Python reference in all four units", {
  b <- cqtna_unit_sweep(mr)
  for (u in c("record", "variant", "gene", "locus")) {
    row <- b[b$unit == u, ]
    for (k in c("n_tests", "n_significant", "n_genes", "n_loci"))
      expect_equal(as.numeric(row[[k]]), refv[[paste0("B.", u, ".", k)]],
                   info = paste(u, k))
  }
})

test_that("module C matches the Python reference", {
  s <- cqtna_stability(mr, alt)
  expect_equal(s$genes_shared, as.integer(refv[["C.genes_shared"]]))
  expect_equal(r3(s$jaccard_gene), refv[["C.jaccard_gene"]])
  expect_equal(r3(s$jaccard_locus), refv[["C.jaccard_locus"]])
  expect_equal(s$loci_shared, as.integer(refv[["C.loci_shared"]]))
  expect_equal(s$loci_outcome1, as.integer(refv[["C.loci_outcome1"]]))
  expect_equal(s$loci_outcome2, as.integer(refv[["C.loci_outcome2"]]))
  for (k in c("gene_variant_pairs_shared", "gene_variant_pairs_only1",
              "gene_variant_pairs_only2"))
    expect_equal(as.numeric(s$coverage[[k]]), refv[[paste0("C.coverage.", k)]],
                 info = k)
})

test_that("module D matches the Python reference", {
  d <- cqtna_ladder(cqtna_demo("instruments"))
  for (k in c("pathway_genes", "instrumentable", "analysable", "associated"))
    expect_equal(as.numeric(d[[k]]), refv[[paste0("D.", k)]], info = k)
})

test_that("module G matches the Python reference on both sweeps", {
  g <- cqtna_window_sweep(mr, kn)
  for (i in seq_len(nrow(g$known_sweep))) {
    kb <- g$known_sweep$known_window_kb[i]
    pre <- paste0("G.known.", kb, ".")
    expect_equal(r2(g$known_sweep$fold[i]), refv[[paste0(pre, "fold")]],
                 info = paste("known", kb))
    expect_equal(g$known_sweep$fisher_p_one_sided[i],
                 refv[[paste0(pre, "fisher_p_one_sided")]], tolerance = 1e-12)
    expect_equal(as.numeric(g$known_sweep$background_known[i]),
                 refv[[paste0(pre, "background_known")]])
  }
  for (i in seq_len(nrow(g$locus_sweep))) {
    kb <- g$locus_sweep$locus_window_kb[i]
    pre <- paste0("G.locus.", kb, ".")
    expect_equal(r2(g$locus_sweep$fold[i]), refv[[paste0(pre, "fold")]],
                 info = paste("locus", kb))
    expect_equal(as.numeric(g$locus_sweep$background_loci[i]),
                 refv[[paste0(pre, "background_loci")]])
  }
})

test_that("module G distances match the Python reference exactly", {
  g <- cqtna_window_sweep(mr, kn)
  want <- refv[grep("^G\\.dist\\.", names(refv))]
  want <- want[order(as.integer(sub("^G\\.dist\\.", "", names(want))))]
  expect_equal(as.numeric(g$significant_distances_bp), as.numeric(want))
})
